//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWalker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        public int WalkerID { get; set; }
        public Nullable<int> AchievementNumber { get; set; }
        public int AchievementID { get; set; }
    
        public virtual Walker Walker { get; set; }
    }
}
