//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWalker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string CommentText { get; set; }
        public Nullable<int> CommenterID { get; set; }
        public Nullable<int> CommentPostID { get; set; }
        public int CommentID { get; set; }
    
        public virtual Comment Comment1 { get; set; }
        public virtual Comment Comment2 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Post Post { get; set; }
    }
}
